version: "3"

networks:
  basic:

services: 
  fastapi:
    container_name: fastapi
    build: ./app
    tty: true
    restart: always
    command: >
      bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8080"
    depends_on:
      #  - mysql
      mysql:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - .:/app
    networks:
      - basic

  mysql:
    image: mysql:8.0.21
    platform: linux/x86_64
    container_name: mysql
    ports:
    - 3306:3306
    restart: always
    networks:
      - basic
    tty: true
    volumes:
      # 永続化するときにマウントするディレクトリ
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/mysql_conf/my.cnf/:/etc/mysql/conf.d/my.cnf
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: calendar
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    command: mysqld --explicit_defaults_for_timestamp=true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
