name: Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint
      run: |
        pip install black==21.9b0 flake8==4.0.1 mypy==0.910 types-requests==2.25.11 types-PyYAML==5.4.12
        flake8 .
        mypy .
        black --check .